#!/bin/bash

language_dir=test/fixtures/tree-sitter-python
language_url=https://github.com/tree-sitter/tree-sitter-python

if [ ! -d $language_dir ]; then
  git clone $language_url $language_dir --depth=1
fi

(
  cd $language_dir
  git fetch origin master --depth 1
  git reset --hard FETCH_HEAD
)
